plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Exclude:
  - "lib/mars/workflows/parallel.rb"

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
